---

- name: Install Ansible Python 2 Dependencies
  dnf:
    name: 
      - python3-firewall
      - python3
      - firewalld
    state: present

- name: Allow https trafic
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: Unencrypted trafic still needed
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Restart firewall
  service:
    name: firewalld
    state: restarted

# setsebool -P httpd_can_network_connect true
- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

