---

- name: Install Ansible Python 2 Dependencies
  dnf:
    name: 
      - python3-firewall
      - python3
      - firewalld
      - python2-libsemanage
      - python3-libsemanage
    state: present

- name: Allow https trafic
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: Unencrypted trafic still needed
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Restart firewall
  service:
    name: firewalld
    state: restarted

# setsebool -P httpd_can_network_connect true
- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Set domain_can_mmap_files flag on and keep it persistent across reboots
  seboolean:
    name: domain_can_mmap_files
    state: yes
    persistent: yes

- name: Set httpd_can_connect_ldap flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_connect_ldap
    state: yes
    persistent: yes

- name: Set httpd_can_network_relay flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_relay
    state: yes
    persistent: yes

- name: copy selinux nginx custom policy
  copy: 
    src: files/mypol.te
    dest: /root/mypol.te

- name: copy selinux nginx custom policy
  copy: 
    src: files/mypol.pp
    dest: /root/mypol.pp

- name:  enable nginx custom selinux policy
  shell: semodule -i /root/mypol.pp


- name: disable selinux
  selinux:
    state: disabled
  when: disable_selinux

